""" Soar v0.11.0 client common constants

Contains named constants for sending messages to the client and determining the type of a controller.
"""
# Client messages
MAKE_GUI = 'MAKE_GUI'
LOAD_BRAIN = 'LOAD_BRAIN'
LOAD_WORLD = 'LOAD_WORLD'
MAKE_CONTROLLER = 'MAKE_CONTROLLER'
START_CONTROLLER = 'START_CONTROLLER'
PAUSE_CONTROLLER = 'PAUSE_CONTROLLER'
STEP_CONTROLLER = 'STEP_CONTROLLER'
STOP_CONTROLLER = 'STOP_CONTROLLER'
SHUTDOWN_CONTROLLER = 'SHUTDOWN_CONTROLLER'
CONTROLLER_COMPLETE = 'CONTROLLER_COMPLETE'
CONTROLLER_SOFT_ERROR = 'CONTROLLER_SOFT_ERROR'
CONTROLLER_IO_ERROR = 'CONTROLLER_IO_ERROR'
CONTROLLER_FAILURE = 'CONTROLLER_FAILURE'
LOGGING_ERROR = 'LOGGING_ERROR'
STEP_FINISHED = 'STEP_FINISHED'
GUI_LOAD_BRAIN = 'GUI_LOAD_BRAIN'
GUI_LOAD_WORLD = 'GUI_LOAD_WORLD'
NOP = 'NOP'

# Messages shared between the client and UI
DRAW = 'DRAW'
CLOSE_LINKED = 'CLOSE_LINKED'
CLOSE_ALL = 'CLOSE_ALL'
MAKE_WORLD_CANVAS = 'MAKE_WORLD_CANVAS'
RELOAD_FINISHED = 'RELOAD_FINISHED'
GUI_ERROR = 'GUI_ERROR'

# Other constants
SIM = 'SIM'
REAL = 'REAL'
EXCEPTION = 'EXCEPTION'
